In [1]:
import numpy as np

In [2]:
# Array 1d

d1 = np.array([1, 2, 3])
print(d1)

[1 2 3]


In [3]:
d1.shape

(3,)

In [5]:
d1.ndim

1

In [6]:
d1.dtype

dtype('int64')

In [7]:
# Arrays 2d

d2 = np.array([[1,2,3], [4, 5, 6]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [8]:
d2.shape

(2, 3)

In [10]:
d2.ndim

2

In [11]:
d2.dtype

dtype('int64')

In [12]:
# Array 3D

d3 = np.array([[[1,2],[2,3]],[[3,4],[4,5]]])
print(d3)

[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]


In [13]:
d3.shape

(2, 2, 2)

In [14]:
d3.ndim

3

In [15]:
d3.dtype

dtype('int64')